# TEST CASE 001: Two-bus system

from uqgrid.psysdef import Psystem, GenGENROU, ExcESDC1A, GovIEESGO, MotCIM5
from uqgrid.uqgrid import integrate_system, initialize_system
from uqgrid.parse import load_psse, add_dyr
from uqgrid.pflow import runpf

import unittest
import numpy as np

# Build system
@unittest.skip("temporarily disabled")
class TestCase(unittest.TestCase):
    
    def test_CIM5(self):

        psys = load_psse(raw_filename="data/2bus_CIM5.raw")
        add_dyr(psys, "data/2bus_CIM5.dyr")
        psys.createYbusComplex()
        v, Pinj = runpf(psys, verbose=False)
        z0, theta = initialize_system(v, Pinj, psys)

        # I verified initialized values match PSSE (except E'q which is just
        # the negative). This array was generated by CLARKE.
        z0_test = np.array([1.06282789e+00,  5.14334118e-01,  8.53109807e-01,
            -6.57036624e-01, 2.90805684e-26,  7.29443915e-01,  9.14245816e-02,
            9.62907965e-01, 1.75465003e-02, 7.75366929e-01,  6.93113357e-01,
            4.58408305e-01, 9.87838359e-01, 3.56846383e-01,  2.87130721e-01,
            1.04000000e+00, -0.00000000e+00, 1.01670401e+00, -5.66480156e-02])
        self.assertTrue(np.allclose(z0_test, z0), 'initialization differs')
